

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: website
      POSTGRES_USER: website
      POSTGRES_PASSWORD: 9382


  web:
    build: .
    command: gunicorn website_back.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DB_NAME=website
      - DB_USER=website
      - DB_PASSWORD=9382
      - DB_HOST=db
      - DB_PORT=5432
